name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd app
          python3 -m unittest discover -p "*.py" > output.txt
          coverage run -m unittest discover
          coverage report
      - name: Save test results
        uses: actions/upload-artifact@v2
        with:
          name: Test results coverage
          path: .coverage output.txt