name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        env:
          DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
        run: |
          cd app
          coverage run -m unittest discover -p "*.py" | tee output.txt
          coverage report
      - name: Save test results
        uses: actions/upload-artifact@v3
        with:
          name: Test results coverage
          path: app/output.txt app/.coverage
