name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage and xml report
        env:
          DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
        run: |
          cd app
          coverage run -m unittest discover
          coverage report > coverage.txt
          python -m coverage html
          python -m xmlrunner discover
      - name: Save coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: app/coverage.txt
      - name: Save coverage html results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html-report
          path: app/htmlcov
      - name: Upload xml report
        uses: actions/upload-artifact@v3
        with:
          name: xml-report
          path: '**/*.xml'
